name: CI build
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v4.2.1
        with:
          fetch-depth: 0
      - name: Setup Go Version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v6.0.0
        with:
          version: latest
          args: release --snapshot --skip=publish --rm-dist
